# Generated by Django 5.0.6 on 2024-11-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_any'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Any',
        ),
    ]
